-- Hand-written. Not generated by drizzle-kit — do not regenerate over this file.
--
-- Three things Drizzle does not model, all of which are security or correctness
-- invariants rather than structure:
--
--   1. Row-level security on every table (PLAN §11).
--   2. Tenant-integrity composite foreign keys, which close a hole RLS alone
--      leaves open (see below).
--   3. The deferred zero-sum constraint trigger for double-entry (PLAN D1).

-- ── 1. Tenant integrity ─────────────────────────────────────────────────────
--
-- RLS stops user B from *reading* user A's rows, but foreign-key checks run
-- with RLS bypassed. Without the composite keys below, B could insert an entry
-- carrying `user_id = B` that references A's `transaction_id`. B cannot see the
-- result, but the zero-sum trigger sums every entry for that transaction
-- regardless of owner — so B could unbalance A's ledger, or block A's writes.
--
-- Making (id, user_id) the referenced key forces every child row to belong to
-- the same tenant as its parent, structurally.

ALTER TABLE "transactions" ADD CONSTRAINT "transactions_id_user_key" UNIQUE ("id", "user_id");
--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_id_user_key" UNIQUE ("id", "user_id");
--> statement-breakpoint
ALTER TABLE "instruments" ADD CONSTRAINT "instruments_id_user_key" UNIQUE ("id", "user_id");
--> statement-breakpoint

ALTER TABLE "entries" DROP CONSTRAINT "entries_transaction_id_transactions_id_fk";
--> statement-breakpoint
ALTER TABLE "entries" DROP CONSTRAINT "entries_account_id_accounts_id_fk";
--> statement-breakpoint

ALTER TABLE "entries" ADD CONSTRAINT "entries_transaction_tenant_fk"
  FOREIGN KEY ("transaction_id", "user_id") REFERENCES "transactions" ("id", "user_id")
  ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE "entries" ADD CONSTRAINT "entries_account_tenant_fk"
  FOREIGN KEY ("account_id", "user_id") REFERENCES "accounts" ("id", "user_id")
  ON DELETE RESTRICT;
--> statement-breakpoint

ALTER TABLE "prices" DROP CONSTRAINT "prices_instrument_id_instruments_id_fk";
--> statement-breakpoint
ALTER TABLE "prices" ADD CONSTRAINT "prices_instrument_tenant_fk"
  FOREIGN KEY ("instrument_id", "user_id") REFERENCES "instruments" ("id", "user_id")
  ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE "allocation_suggestions"
  DROP CONSTRAINT "allocation_suggestions_trigger_transaction_id_transactions_id_fk";
--> statement-breakpoint
ALTER TABLE "allocation_suggestions" ADD CONSTRAINT "allocation_suggestions_txn_tenant_fk"
  FOREIGN KEY ("trigger_transaction_id", "user_id") REFERENCES "transactions" ("id", "user_id")
  ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE "recurrences" DROP CONSTRAINT "recurrences_template_transaction_id_transactions_id_fk";
--> statement-breakpoint
ALTER TABLE "recurrences" ADD CONSTRAINT "recurrences_template_tenant_fk"
  FOREIGN KEY ("template_transaction_id", "user_id") REFERENCES "transactions" ("id", "user_id")
  ON DELETE CASCADE;
--> statement-breakpoint

-- ── 2. Double-entry zero-sum ────────────────────────────────────────────────
--
-- Deferred to COMMIT because a balanced transaction is necessarily unbalanced
-- part-way through inserting its own entries.

CREATE OR REPLACE FUNCTION "public"."assert_transaction_balanced"()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $fn$
DECLARE
  v_txn   uuid;
  v_sum   bigint;
  v_count integer;
BEGIN
  v_txn := COALESCE(NEW."transaction_id", OLD."transaction_id");

  SELECT COALESCE(SUM("amount_hkd_minor"), 0), COUNT(*)
    INTO v_sum, v_count
    FROM "public"."entries"
   WHERE "transaction_id" = v_txn;

  -- Zero entries means the parent transaction was deleted and its entries
  -- cascaded. Nothing to balance.
  IF v_count = 0 THEN
    RETURN NULL;
  END IF;

  IF v_count < 2 THEN
    RAISE EXCEPTION
      'transaction % has % entry: double-entry requires at least 2', v_txn, v_count
      USING ERRCODE = 'check_violation';
  END IF;

  IF v_sum <> 0 THEN
    RAISE EXCEPTION
      'transaction % entries sum to % HKD minor units, must be 0', v_txn, v_sum
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$fn$;
--> statement-breakpoint

CREATE CONSTRAINT TRIGGER "entries_balanced"
  AFTER INSERT OR UPDATE OR DELETE ON "entries"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION "public"."assert_transaction_balanced"();
--> statement-breakpoint

-- ── 3. Row-level security ───────────────────────────────────────────────────
--
-- Applied by loop over an explicit table list. The list is visible for review,
-- and the loop guarantees no table gets a hand-typed policy that quietly
-- differs from the others — missing or divergent policies being the actual
-- failure mode here.
--
-- `(SELECT auth.uid())` rather than a bare call: the planner hoists it to an
-- InitPlan and evaluates it once per query instead of once per row.

DO $rls$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'accounts',
    'categories',
    'transactions',
    'entries',
    'instruments',
    'prices',
    'fx_rates',
    'recurrences',
    'allocation_suggestions',
    'ingest_sources',
    'rule_settings'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);

    EXECUTE format(
      'CREATE POLICY %I ON public.%I
         FOR ALL TO authenticated
         USING ("user_id" = (SELECT auth.uid()))
         WITH CHECK ("user_id" = (SELECT auth.uid()))',
      t || '_owner', t
    );

    -- Anonymous callers get no policy at all, so they see nothing. Revoking
    -- explicitly makes that intent legible rather than implied.
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
  END LOOP;
END
$rls$;
